#!/bin/bash
# .xprofile

# pc specific settings
case "$(cat /etc/hostname)" in
    "tipc")
        compton -t -8 -l -8 -o 1.0 -D 4 -r 5 -m 0.9 &
        setxkbmap gb
        xset s off -dpms
        ;;
    *)
        setxkbmap -layout de -variant nodeadkeys
        xset +dpms
        xset dpms 0 0 1860
        xset s off
        ;;
esac

# general settings
xautolock -time 30 -locker "i3lock-fancy -p -t ''" &

(
    loger=".xlog";
    sleep 1;
    if [[ -f $HOME/.screenlayout/mega.sh ]]; then
        echo "mega" > $loger;
        source $HOME/.screenlayout/mega.sh;
    fi
    sleep 1;
    if [[ -f $HOME/.feh_update.sh ]]; then
        echo "feh" >> $loger;
        source $HOME/.feh_update.sh &
    fi
    echo "xfce" >> $loger;
    /usr/lib64/xfce4/notifyd/xfce4-notifyd
)&

# remember to start illum-d via cron if
# your graphics driver doesn't support the fn-keys
